concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "rustpress-runner"
  url = "http://host.docker.internal:8080"
  id = 3
  token = "glrtr-XAsnp_OLa-yjnfTzLM9rbG86MQpwOjEKdDozCw.01.1217vg7dg"
  token_obtained_at = 2025-12-25T13:44:23Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://host.docker.internal:8080"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "rust:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["gitlab.local:host-gateway"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "rustpress-project-runner"
  url = "http://host.docker.internal:8080"
  id = 4
  token = "glrtr-3mx69Bp7BQbUD22y39koY286MQpwOmgKdDozCw.01.121g10amh"
  token_obtained_at = 2025-12-26T04:53:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://host.docker.internal:8080"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "rust:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["gitlab.local:host-gateway"]
    shm_size = 0
    network_mtu = 0
